// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/fingo-martPedia/fingo-ums/helpers"
	"github.com/fingo-martPedia/fingo-ums/internal/api"
	"github.com/fingo-martPedia/fingo-ums/internal/interfaces"
	"github.com/fingo-martPedia/fingo-ums/internal/repository"
	"github.com/fingo-martPedia/fingo-ums/internal/services"
	"gorm.io/gorm"
)

// Injectors from injector.go:

func InitDependency() Dependency {
	db := provideDB()
	userRepository := repository.NewUserRepository(db)
	healthcheck := services.NewHealthcheckService()
	apiHealthcheck := api.NewHealthcheckHandler(healthcheck)
	loginService := services.NewLoginService(userRepository)
	loginHandler := api.NewLoginHandler(loginService)
	registerService := services.NewRegisterService(userRepository)
	registerHandler := api.NewRegisterHandler(registerService)
	logoutService := services.NewLogoutService(userRepository)
	logoutHandler := api.NewLogoutHandler(logoutService)
	refreshTokenService := services.NewRefreshTokenService(userRepository)
	refreshTokenHandler := api.NewRefreshTokenHandler(refreshTokenService)
	dependency := Dependency{
		UserRepository:  userRepository,
		HealthcheckAPI:  apiHealthcheck,
		LoginAPI:        loginHandler,
		RegisterAPI:     registerHandler,
		LogoutAPI:       logoutHandler,
		RefreshTokenAPI: refreshTokenHandler,
	}
	return dependency
}

// injector.go:

type Dependency struct {
	UserRepository interfaces.IUserRepository

	HealthcheckAPI  interfaces.IHealthcheckHandler
	LoginAPI        interfaces.ILoginHandler
	RegisterAPI     interfaces.IRegisterHandler
	LogoutAPI       interfaces.ILogoutHandler
	RefreshTokenAPI interfaces.IRefreshTokenHandler
}

func provideDB() *gorm.DB {
	return helpers.DB
}
